### ISSUE TITLE
Mod isnt in the load order 

### ISSUE THREAD

**Issue by Cerberus610** [Evanidus14/Aldrnari-Gamepad-Setup#3]
I've been spending time trying to find this file in MO and the load order and haven't seen it. It's been takin out? Im probably one of the few players that plays skyrim on a game pad .

**Comment by Evanidus14** [comment]
Are you using the most up to date version of the modlist? You need to be using Aldrnari Version 1.1. Expand the "generated Files" separator in MO2 (Down at the bottom of the main pane in MO2) and you'll see the mod "Gamepad Specific - Modified ControlMap.txt" enable it. Then just keep following the readme.
